// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	bar "boilerplate/internal/repositiories/bar"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindUserByBars provides a mock function with given fields: ctx, _a1
func (_m *Repository) FindUserByBars(ctx context.Context, _a1 string) ([]*bar.User, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []*bar.User
	if rf, ok := ret.Get(0).(func(context.Context, string) []*bar.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*bar.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
